export const UPDATE_MOVIES = "UPDATE_MOVIES";
export const UPDATE_SEARCH_MOVIES = "UPDATE_SEARCH_MOVIES";
export const REMOVE_MOVIE = "REMOVE_MOVIE";
export const SET_CURRENT_MOVIE = "SET_CURRENT_MOVIE";
export const ADD_MOVIE = "ADD_MOVIE";
export const LOADING = "LOADING";

export const ADD_FAVORITE = "ADD_FAVORITE";
export const REMOVE_FAVORITE = "REMOVE_FAVORITE";
export const UPDATE_FAVORITES = "UPDATE_FAVORITES";
